import java.util.ArrayList;

public class TeacherData {
    public static ArrayList<Teachers> teacherData() {
        String[] staffList = {
                "Ms. Angelene Alberga, Biological Sciences",
                "Mr. James Bacchi, Biological Sciences",
                "Ms. Victoria Cheng, Biological Sciences",
                "Ms. Stephanie Doire, Biological Sciences",
                "Dr. Michael Estrella, Biological Sciences",
                "Mr. Justin Fabrikant, Biological Sciences",
                "Mr. Colvin Gibson, Biological Sciences",
                "Ms. Areej Hafeez, Biological Sciences",
                "Mr. Eric Hou, Biological Sciences",
                "Ms. Diana Lennon, Biological Sciences",
                "Ms. Kelly Lovelett, Biological Sciences",
                "Dr. Elisa Margarita, Biological Sciences",
                "Mr. Sean McCaffery, Biological Sciences",
                "Mr. Hadi Nasrollahi, Biological Sciences",
                "Ms. Donna Nathan, Biological Sciences",
                "Mrs. Iwona O'Brien, Biological Sciences",
                "Mrs. Brenda Oquendo-Orna, Biological Sciences",
                "Mrs. Caitlin Reste, Biological Sciences",
                "Mr. Jason Sheldon, Biological Sciences",
                "Ms. Jessica Tagliarino, Biological Sciences",
                "Mr. Devin Thomas, Biological Sciences",
                "Ms. Zonia Adalat, Chemistry",
                "Ms. Lisa Carter Serrette, Chemistry",
                "Mr. Callistus Chiemezie, Chemistry",
                "Mr. Thomas Evangelist, Chemistry",
                "Mr. Joseph Gerraputa, Chemistry",
                "Ms. Melissa Greene, Chemistry",
                "Ms. Stephanie Henry, Chemistry",
                "Mr. Leonid Kantorovich, Chemistry",
                "Ms. Iqra Khan, Chemistry",
                "Mr. Yongjun Lee, Chemistry",
                "Ms. Caroline Leonard, Chemistry",
                "Mr. Shi Lin, Chemistry",
                "Ms. Christa Martin, Chemistry",
                "Mr. Matthew Mecner, Chemistry",
                "Ms. Patricia Multari, Chemistry",
                "Mr. Sooraj Nair, Chemistry",
                "Mr. Conrad Richman, Chemistry",
                "Ms. Shirley Shameen, Chemistry",
                "Dr. Joseph Shtab, Chemistry",
                "Dr. Horace Walcott, Chemistry",
                "Mr. Ivan Turner, CTE, Computer Science & Engineering",
                "Mr. Miguel Zeng, CTE, Computer Science & Engineering",
                "Ms. Vickie Albury, CTE, Computer Science & Engineering",
                "Kuvar Bhatnagar, CTE, Computer Science & Engineering",
                "Mr. Carlos Blackwood, CTE, Computer Science & Engineering",
                "Mr. Michael Boulis, CTE, Computer Science & Engineering",
                "Ms. Alise Braick, CTE, Computer Science & Engineering",
                "Ms. Wandy Chang, CTE, Computer Science & Engineering",
                "Mr. Luis Collado, CTE, Computer Science & Engineering",
                "Mr. Rupesh Das, CTE, Computer Science & Engineering",
                "Ms. Shaina Doherty, CTE, Computer Science & Engineering",
                "Mr. Adam Driggers, CTE, Computer Science & Engineering",
                "Ms. Jessica Du Ward, CTE, Computer Science & Engineering",
                "Mr. Nathan Folwell, CTE, Computer Science & Engineering",
                "Mr. Ali Harb, CTE, Computer Science & Engineering",
                "Mr. Quincy Holmer, CTE, Computer Science & Engineering",
                "Mr. Iulian Irimina, CTE, Computer Science & Engineering",
                "Emile Jean Bapiste, CTE, Computer Science & Engineering",
                "Ms. Reina Joa, CTE, Computer Science & Engineering",
                "Ms. Rachel Kaufman, CTE, Computer Science & Engineering",
                "Mr. Hoiming Bonny Lee, CTE, Computer Science & Engineering",
                "Mr. Tsee Lee, CTE, Computer Science & Engineering",
                "Mr. Rick Lopez, CTE, Computer Science & Engineering",
                "Mr. Timothy Lyons, CTE, Computer Science & Engineering",
                "Mr. Mike Miller, CTE, Computer Science & Engineering",
                "Mr. Luke Moffit, CTE, Computer Science & Engineering",
                "Ms. Marina Moshchenko, CTE, Computer Science & Engineering",
                "Dr. Thomas Price, CTE, Computer Science & Engineering",
                "Mr. Mark Rodriguez, CTE, Computer Science & Engineering",
                "Ms. Tatiana Turin, CTE, Computer Science & Engineering",
                "Ms. Tiffany Wong, CTE, Computer Science & Engineering",
                "Mr. Matthew Adelizzi, English",
                "Mr. Samuel Armen, English",
                "Ms. Erin Beach, English",
                "Ms. Lisa Bensing, English",
                "Ms. Jess Rhoades Bonilla, English",
                "Ms. JoAnna Bueckert-Chan, English",
                "Mr. Richard Capozzi, English",
                "Ms. Sandra Del Valle, English",
                "Mr. David Der Sarkisian, English",
                "Ms. Joanna Drusin, English",
                "Ms. Joy Ferguson, English",
                "Ms. Elizabeth Filippelli, English",
                "Mr. Zachary Gale, English",
                "Ms. Melissa Goodrum, English",
                "Mrs. Tatyana Green, English",
                "Mr. Stephen Harris, English",
                "Mr. Willie Ho, English",
                "Ms. Farhana Hoque, English",
                "Ms. Kaitlyn Huczko, English",
                "Mr. Elliott Johnston, English",
                "Ms. Katrina Kaplan, English",
                "Ms. Jennifer Kim, English",
                "Mr. Avram Kline, English",
                "Mr. Joel Lederer, English",
                "Ms. Diana Liu, English",
                "Mr. Evan Losow, English",
                "Ms. Elizabeth Lvov, English",
                "Ms. Ariel Marcus, English",
                "Ms. Christina Massie, English",
                "Ms. Robin McCullough, English",
                "Ms. Jennifer Mikitanov, English",
                "Ms. Gabriella Newton, English",
                "Mr. Kemp Pettyjohn, English",
                "Mrs. Stephanie Galvin Pollicino, English",
                "Mr. Timothy Ree, English",
                "Ms. Samantha Seide, English",
                "Ms. Sandhya Seshan, English",
                "Dr. Sujay Sood, English",
                "Ms. Jessica Spinosa, English",
                "Ms. Vesna Sukalo, English",
                "Ms. Judith Taveras, English",
                "Mr. Edwin Velazquez, English",
                "Mr. Adam Virzi, English",
                "Mr. Israel Wasserstein, English",
                "Mr. David Whitman, English",
                "Ms. Irene Yannascoli, English",
                "Ms. Izumi Yoshioka, English",
                "Agape Alexander, Health & PE",
                "Mrs. Lucy Balansag, Health & PE",
                "A Besler, Health & PE",
                "Mr. Todd Bloom, Health & PE",
                "Mr. Jean Brutus, Health & PE",
                "Mr. Anthony Cicolini, Health & PE",
                "Ms. Brianne Cicolini, Health & PE",
                "Ms. Jacklyn Diel, Health & PE",
                "Ms. Gianna Forni, Health & PE",
                "Mr. Stephen Gigliello, Health & PE",
                "Mr. Pratheip Gugendiran, Health & PE",
                "Mr. Joni Lamani, Health & PE",
                "Ms. Maureen Malone, Health & PE",
                "Mr. Joseph Maro, Health & PE",
                "Mr. Joseph Nardiello, Health & PE",
                "Ms. Sarah Nolan, Health & PE",
                "Mrs. Lori (Turk) Parizman, Health & PE",
                "Ms. Stacey Patti, Health & PE",
                "Mr. Josh Rubin, Health & PE",
                "Ms. Joy San Agustin, Health & PE",
                "Ms. Carla Sigona, Health & PE",
                "Ms. Nicole Stuart, Health & PE",
                "Mr. Derek Swartz, Health & PE",
                "Mr. Austin Tennenbaum, Health & PE",
                "Ms. Christina Aguis, Mathematics",
                "Mr. Daniel Amato, Mathematics",
                "Mr. James Bathurst, Mathematics",
                "Ms. Melanie Battles, Mathematics",
                "Ms. Heather Berry, Mathematics",
                "Ms. Jane Bolles, Mathematics",
                "Mr. Nathan Bonheimer, Mathematics",
                "Ms. Shubhra Breivogel, Mathematics",
                "Ms. Alexandra Brennan, Mathematics",
                "Ms. Oyinka Bruce, Mathematics",
                "Ms. Carrie Chu, Mathematics",
                "Ms. Julia Debenedetto, Mathematics",
                "Mr. Vincent Ewing, Mathematics",
                "Ms. Kiersten Franz, Mathematics",
                "Ms. Nina Granberry, Mathematics",
                "Ms. Linda Hoftyzer, Mathematics",
                "Ms. Amy Hogan, Mathematics",
                "Ms. Danrong Huang, Mathematics",
                "Graeme Hunter, Mathematics",
                "Mr. Stan Kats, Mathematics",
                "Ms. Malgorzata Kurzyna, Mathematics",
                "Ms. Amy Lee, Mathematics",
                "Mr. Amos Levy, Mathematics",
                "Mr. Benjamin Lockeretz, Mathematics",
                "Ms. Rita Loomba, Mathematics",
                "Mr. Scott Matthews, Mathematics",
                "Ms. Brigid Moran, Mathematics",
                "Mr. Ben Morgenroth, Mathematics",
                "Mr. Arup Mukherjee, Mathematics",
                "Ms. Vivi Nguyen, Mathematics",
                "Mr. Edward Orna, Mathematics",
                "Mr. Andrew Ostrowsky, Mathematics",
                "Ms. Joyce Pan, Mathematics",
                "Ms. Kathryn Quinn, Mathematics",
                "Mr. Kenneth Raftery, Mathematics",
                "Mr. Raul Saenz, Mathematics",
                "Mr. Bruce Samuels, Mathematics",
                "Mr. Michael Schillaci, Mathematics",
                "Mr. Hemal Shah, Mathematics",
                "Mr. Doug Shuman, Mathematics",
                "Mr. Dustin Shutes, Mathematics",
                "Mr. Steven Stein, Mathematics",
                "Ms. Chrystalleni Stivaros, Mathematics",
                "Ms. Lydia Yale, Mathematics",
                "Ms. Patricia Yee, Mathematics",
                "Mr. David Adams, Physics",
                "Mr. Mohammed Alomeri, Physics",
                "Mr. Rashidul Bari, Physics",
                "Mr. Raymond Bradshaw, Physics",
                "Mr. Andrew Brickman, Physics",
                "Mr. Christian Corrao, Physics",
                "Ms. Kathleen Davey, Physics",
                "Mr. Thomas Duncan, Physics",
                "Mr. Thomas Evangelist, Physics",
                "Mr. Jacob Geier, Physics",
                "Mr. Bruce Greenspan, Physics",
                "Mr. John Haggerty, Physics",
                "Mr. Todd Hatch, Physics",
                "Mr. Steven Herbst, Physics",
                "Mr. Thomas Murawski, Physics",
                "Mr. Joshua Paugh, Physics",
                "Mr. Rivera Samuel, Physics",
                "Ms. Rachel Sardo, Physics",
                "Mr. Jose Vargas, Physics",
                "Ms. Nancy Yi, Physics",
                "Mr. Steven Apollon, Social Studies",
                "Mr. Serge Avery, Social Studies",
                "Mr. Alan Barbour, Social Studies",
                "Ms. Allie Carter, Social Studies",
                "Ms. Rosy Castillo, Social Studies",
                "Mr. William Cheung, Social Studies",
                "Ms. Marisa Cirino, Social Studies",
                "Mr. Vincent Dennie, Social Studies",
                "Mr. Jake DiVeronica, Social Studies",
                "Ms. Jennie Ferry, Social Studies",
                "Mr. Joshua Fine, Social Studies",
                "Mr. Joshua Frost, Social Studies",
                "Ms. Elina Galperin, Social Studies",
                "Ms. Rachel Germany, Social Studies",
                "Mr. Dave Gilmore, Social Studies",
                "Mr. Mark Heh, Social Studies",
                "Mr. Evan Hereshinson, Social Studies",
                "Tahan Izzat, Social Studies",
                "Dr. Judith Jeremie, Social Studies",
                "Ms. Elizabeth Johnson, Social Studies",
                "Ms. Rachel Kaplan, Social Studies",
                "Mr. Mark Keller, Social Studies",
                "Mr. Keith Kilgore, Social Studies",
                "Ms. Orli Kleiner, Social Studies",
                "Mr. Jonathan Leaf, Social Studies",
                "Mrs. Robin Levitt (Scherman), Social Studies",
                "Mr. Xu Li, Social Studies",
                "Mr. Philip Linder, Social Studies",
                "Mr. Jeffrey Locke, Social Studies",
                "Ms. Amy Lucisano, Social Studies",
                "Dr. Matthew Maclean, Social Studies",
                "Mr. Andrew Macvicar, Social Studies",
                "Mrs. Beth Malchiodi, Social Studies",
                "Mrs. Jacqueline Manduley, Social Studies",
                "Mr. Josidalgo Martinez, Social Studies",
                "Mr. Francis Mayle, Social Studies",
                "Mr. Sean McManamon, Social Studies",
                "Ms. Victoria Meyer, Social Studies",
                "Mr. Harry Misirlakis, Social Studies",
                "Amani Mohamed, Social Studies",
                "Ms. Kathleen Nadel, Social Studies",
                "Mr. Michael O'Shea, Social Studies",
                "Mr. Jeffrey Park, Social Studies",
                "Mr. Isaiah Pratt, Social Studies",
                "Ms. I Ramnath, Social Studies",
                "Ms. Monica Robinson-Bynum, Social Studies",
                "Mr. David Schepard, Social Studies",
                "Mr. Peter Schmidt-Nowara, Social Studies",
                "Ms. Samantha Schoeller, Social Studies",
                "Mr. Joshua Silverman, Social Studies",
                "Mr. Elijah Singh, Social Studies",
                "Mr. Stephen Stavola, Social Studies",
                "Mr. Richard Stein, Social Studies",
                "Mr. Adam Stevens, Social Studies",
                "Mr. Will Treece, Social Studies",
                "Mr. Luis Vergara, Social Studies",
                "Mr. Thomas Wentworth, Social Studies",
                "Ms. Rachel Worrell, Social Studies",
                "Ms. Maria Zagoreos, Social Studies",
                "Edward Abdenour, Special Education",
                "Ms. Annalise Armenta, Special Education",
                "Ms. Dema Bader, Special Education",
                "Mr. Artur Balanovskiy, Special Education",
                "Mr. Samuel Briante, Special Education",
                "Mr. Jacob Brodsky, Special Education",
                "Mr. Marlon Esguerra, Special Education",
                "Ms. Jeannette Gambale, Special Education",
                "Ms. Erica Gindi, Special Education",
                "Ms. Jade Hall, Special Education",
                "Mrs. Malicka Hung, Special Education",
                "Ms. Jacqueline Jezioro, Special Education",
                "Ms. Tiffany Johnson, Special Education",
                "Ms. Esther Kabalkin, Special Education",
                "Ms. Laura Lachance, Special Education",
                "Mr. Kellan Mansano, Special Education",
                "Mr. John McGrane, Special Education",
                "Mr. Tim Monti-Wohlpart, Special Education",
                "Ms. Jossie Montolio, Special Education",
                "Ms. Amanda Moreno, Special Education",
                "Mr. Rati Mukhuradze, Special Education",
                "Ms. Lisa O'Kane, Special Education",
                "Mr. Barrington Bigsby, Visual & Performing Arts",
                "Mr. Steve Coyle, Visual & Performing Arts",
                "Mrs. Patricia DePinto, Visual & Performing Arts",
                "Mr. Richard Depinto, Visual & Performing Arts",
                "Ms. Connie Eng, Visual & Performing Arts",
                "Mr. Michael Fisher, Visual & Performing Arts",
                "Mr. Park K Fung, Visual & Performing Arts",
                "Mr. Yesid Gonzalez, Visual & Performing Arts",
                "Mr. Michael Guldal, Visual & Performing Arts",
                "Mr. Sidney Izakson, Visual & Performing Arts",
                "Mr. Rudy M, Visual & Performing Arts",
                "Ms. Katherine Minkoff, Visual & Performing Arts",
                "Ms. Basia Revi, Visual & Performing Arts",
                "Mr. Evan Schwartz, Visual & Performing Arts",
                "Rich Singler, Visual & Performing Arts",
                "Mr. Alexander Tasopoulos, Visual & Performing Arts",
                "Mr. Garfield Taylor, Visual & Performing Arts",
                "Mr. Gustave Trombetta, Visual & Performing Arts",
                "Mr. Richard Wanliss, Visual & Performing Arts",
                "Mr. Doug Weiner, Visual & Performing Arts",
                "Deshawn Withers, Visual & Performing Arts",
                "Ms. Ana Aguirre, World Languages & ENL",
                "Ms. Michelle Albano, World Languages & ENL",
                "Ms. Luz Rocio Cely, World Languages & ENL",
                "Ms. Yan Chen, World Languages & ENL",
                "Ms. Katherine Cook, World Languages & ENL",
                "Mr. Mario Costa, World Languages & ENL",
                "Mr. Adrian Davila, World Languages & ENL",
                "Ms. Alessandra De Meo, World Languages & ENL",
                "Ms. Maria Jose Entrena, World Languages & ENL",
                "Ms. Eika Gervasi, World Languages & ENL",
                "Ms. Raquel Hornero, World Languages & ENL",
                "Mr. Joshua Hurd, World Languages & ENL",
                "Ms. Rita Iniguez, World Languages & ENL",
                "Ms. Erhhan Kao, World Languages & ENL",
                "Mr. Joon Keum, World Languages & ENL",
                "Mr. Randy Levadas, World Languages & ENL",
                "Ms. Hoi Sha Li, World Languages & ENL",
                "Jiazi Lin, World Languages & ENL",
                "Ms. Valerie Mitchell, World Languages & ENL",
                "Ms. Juana Nava, World Languages & ENL",
                "Mr. Cristobal Petersen, World Languages & ENL",
                "Pierrelyne Pierre, World Languages & ENL",
                "Ms. Lin Rao, World Languages & ENL",
                "Ms. Cristina Santiago-Campbell, World Languages & ENL",
                "Ms. Chung-Chi Sha, World Languages & ENL",
                "Mr. Jean-Paul Torres, World Languages & ENL",
                "Ms. Nancy Villalba, World Languages & ENL",
                "Ms. Ioana Wicker, World Languages & ENL",
                "Ms. Xiaohong Wu, World Languages & ENL",
                "Ms. Peihong Ye, World Languages & ENL"
        };
        ArrayList<Teachers> data = new ArrayList<>();
        for(int i = 0; i < staffList.length; i++){
            String[] values = staffList[i].split(", ");
            if(values[0].contains("'")){
                values[0] = values[0].substring(0, values[0].indexOf("'")) + "'" + values[0].substring(values[0].indexOf("'"));
            }
            if(values[1].equals("Biological Sciences")){
                values[1] = "1";
            }
            else if(values[1].equals("Chemistry")){
                values[1] = "2";
            }
            else if(values[1].equals("CTE")){
                values[1] = "3";
            }
            else if(values[1].equals("English")){
                values[1] = "4";
            }
            else if(values[1].equals("Health & PE")){
                values[1] = "5";
            }
            else if(values[1].equals("Mathematics")){
                values[1] = "6";
            }
            else if(values[1].equals("Physics")){
                values[1] = "7";
            }
            else if(values[1].equals("Social Studies")){
                values[1] = "8";
            }
            else if(values[1].equals("Special Education")){
                values[1] = "9";
            }
            else if(values[1].equals("Visual & Performing Arts")){
                values[1] = "10";
            }
            else if(values[1].equals("World Languages & ENL")){
                values[1] = "11";
            }
            else{
                System.out.println("error");
            }
            data.add(new Teachers(values[0], Integer.parseInt(values[1])));
        }
        return data;
    }
}